### ISSUE TITLE
Allow `repulse` range to be configurable

### ISSUE THREAD

**Issue by crutchcorn** [matteobruni/tsparticles#236]
**Is your feature request related to a problem? Please describe.**
Currently, when using the `onhover` `repulse` mode, there's a radius around the mouse that's much larger than the mouse itself. For my usage of the library, I'd like to shrink that down to roughly the size of the mouse itself

**Describe the solution you'd like**
It would be nice if we're able to pass in a number as a config prop that enables the radius around the hovered mouse to be variable

**Comment by matteobruni** [comment]
`events.modes.repulse.distanze` should be the option you are searching, isn’t it working?

**Comment by crutchcorn** [comment]
@matteobruni oh, okay, I see it now. I think the primary problem I have with lowering it below a certain level is that the movement is super janky. Anything below 100 I find to be almost unusable. For context, I'm using it in `bubble` mode and the movement just seems super jagged at lower levels of movement

**Comment by matteobruni** [comment]
Can you share your config? I’d like to test it, maybe there’s a bug I could fix.

**Comment by crutchcorn** [comment]
Website source can be found at: 

https://github.com/crutchcorn/gitshark-website

And the specific config can be found here: 

https://github.com/crutchcorn/gitshark-website/blob/master/src/components/shark-background/shark-background.jsx#L94

Right now the distance is set to 100, but if it's set to 10, the odd movement behavior is found. 

Also, as an aside, you've done amazing work with maintaining this from ParticleJS. I know how hard maintanance can be and you've simply knocked it out of the park, regardless of what happens with this particular issue

**Comment by matteobruni** [comment]
Thank you so much 😊

I've checked and the issue was on 1.13 alpha as well. I've added a `speed` option to the `repulse` configuration in `1.13.0-alpha.6`.

I've seen you set the distance to 10 but the particles have a size of 20, I'd suggest to have a repulse distance >= of the particles size.

If you want to test the speed you need to update `react-particles-js` to `3.1.0`, this version doesn't include `tsParticles` in its bundle so you can have a different version dependency.

The new `speed` option have `1` as default value, if you want a smoother effect you should use a value between 0 and 1, if you want a faster effect > 1. Remember this is an alpha version and this value range could be changed until release (it could remain the same, I need to do more tests).

If you'll try the alpha version let me know if the movement is working as expected.

**Comment by crutchcorn** [comment]
After testing with the alpha version you suggested, and keeping the particle size `20`, this config had the behavior I was looking for:

```javascript
repulse: {
  distance: 20,
    duration: 1,
    speed: 0.2,
},
```
